### ISSUE TITLE
Code stuck before starting the server

### ISSUE THREAD

**Issue by montefra** [GaretJax/sphinx-autobuild#45] opened 2016-06-02 09:11 UTC
Hi,

recently the autobuild is miss-behaving.

If I run from scratch, it correctly builds the documentation, but then get stuck just before starting the server:

```
| [...]
| dumping search index in English (code: en) ... done
| dumping object inventory... done
| build succeeded, 117 warnings.
```

 If I `ctrl+C` I get:

```
File "/path/to/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
File "/path/to/lib/python3.4/site-  packages/sphinx_autobuild/__init__.py", line 310, in main
    builder.build()
File "/path/to/lib/python3.4/site-packages/sphinx_autobuild/__init__.py", line 183, in build
    line = stdout.readline()
KeyboardInterrupt
Makefile:64: recipe for target 'livehtml' failed
make: *** [livehtml] Error 1
```

If I rerun I get:

```
| no targets are out of date.
| build succeeded.
+--------------------------------------------------------------------------------

[I 160602 10:55:19 server:281] Serving on http://127.0.0.1:8000
[I 160602 10:55:19 handlers:59] Start watching changes
[I 160602 10:55:19 handlers:61] Start detecting changes
```

Then when I modify something, the documentation is rebuilt, but it stop at:

```
| [...]
| dumping search index in English (code: en) ... done
| dumping object inventory... done
| build succeeded, 6 warnings.
```

and `ctrl+c` simply shut down the server.

**Comment by pradyunsg** [comment] 2020-08-20 12:35
Hi!

This is a really old issue, but by any chance, do you know *why* this might have been occurring? And, if someone has a way to reproduce this, that'd be great! :)

**Comment by pradyunsg** [comment] 2020-08-26 18:53
Closing since this is really old and I don't expect OP to respond looking at their GH activity.

**Closed by pradyunsg** 2020-08-26 18:53 UTC
Labels: needs info
